# Generated by Django 2.2.5 on 2019-09-11 23:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='audios/')),
                ('cover', models.ImageField(upload_to='covers/')),
                ('titre', models.TextField(max_length=1000)),
                ('auteur', models.TextField(max_length=1000)),
                ('slug', models.SlugField(max_length=1000)),
                ('anneeSortie', models.DateTimeField(verbose_name='Année de sortie')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PayementMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lumicash', models.IntegerField()),
                ('ecocash', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Payement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField()),
                ('identifiant', models.IntegerField()),
                ('payementMethod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.PayementMethod')),
            ],
        ),
    ]
