# Generated by Django 2.2.5 on 2019-09-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='audio',
            field=models.FileField(upload_to='music/audios/'),
        ),
        migrations.AlterField(
            model_name='music',
            name='cover',
            field=models.ImageField(upload_to='music/covers/'),
        ),
        migrations.AlterField(
            model_name='music',
            name='ringtone',
            field=models.FileField(upload_to='music/audios/ringtone/'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='music/avatars/'),
        ),
        migrations.AlterField(
            model_name='slides',
            name='slides',
            field=models.ImageField(blank=True, null=True, upload_to='music/slides/'),
        ),
    ]
