# Generated by Django 2.2.3 on 2019-09-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='audio',
            field=models.FileField(upload_to='music/audios/'),
        ),
        migrations.AlterField(
            model_name='music',
            name='cover',
            field=models.ImageField(upload_to='music/covers/'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='music/avatars/'),
        ),
    ]
