# Generated by Django 2.2.5 on 2019-09-14 21:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20190914_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compositeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=1000)),
                ('last_name', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField(max_length=1000)),
            ],
        ),
        migrations.RenameField(
            model_name='music',
            old_name='auteur',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='music',
            old_name='anneeSortie',
            new_name='release',
        ),
        migrations.RenameField(
            model_name='music',
            old_name='titre',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='payement',
            old_name='identifiant',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='payement',
            old_name='montant',
            new_name='identification',
        ),
        migrations.RemoveField(
            model_name='payement',
            name='payementMethod',
        ),
        migrations.AddField(
            model_name='music',
            name='ringtone',
            field=models.FileField(default=1, upload_to='audios/ringtone/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payement',
            name='payement_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.PayementMethod'),
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=1000)),
                ('last_name', models.TextField(max_length=1000)),
                ('about', models.TextField(max_length=1000)),
                ('birthday', models.DateTimeField(default=django.utils.timezone.now)),
                ('music', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.Music')),
            ],
        ),
        migrations.AddField(
            model_name='music',
            name='composer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.Compositeur'),
        ),
        migrations.AddField(
            model_name='music',
            name='label',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.Label'),
        ),
    ]
