# Generated by Django 2.2.5 on 2019-09-16 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20190914_2344'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Compositeur',
            new_name='Composer',
        ),
        migrations.RenameField(
            model_name='label',
            old_name='nom',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='music',
        ),
        migrations.AlterField(
            model_name='music',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.Artist'),
        ),
    ]
