# Generated by Django 2.2.3 on 2019-09-08 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BujaMovies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='prix_telechargement',
            field=models.FloatField(default=0.0, verbose_name='Prix de Téléchargement'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Achats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField(verbose_name='Montant')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
