# Generated by Django 2.2.3 on 2019-09-08 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BujaMovies', '0002_auto_20190908_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='achats',
            name='slug',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='BujaMovies.Films'),
        ),
    ]
