from .Ajouter import AjouterView
from .Book import BookView
from .Books import BooksView
from .BooksByAnnee import BooksByAnneeView
from .BooksByAuteur import BooksByAuteurView
from .BooksByCategorie import BooksByCategorieView
from .BooksByMaison import BooksByMaisonView
from .Like import like
from .Modifier import ModifierView
from .Supprimer import SupprimerView