# Generated by Django 2.2.3 on 2019-09-05 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur', models.CharField(max_length=30, verbose_name='auteur du livre')),
                ('maison', models.CharField(max_length=30, verbose_name="maison d'edition")),
                ('titre', models.CharField(max_length=30, verbose_name='titre du livre')),
                ('cover', models.ImageField(upload_to='covers/')),
                ('contenue', models.TextField(verbose_name='le contenue du livre')),
                ('annee', models.DateField(default=django.utils.timezone.now)),
                ('prix', models.IntegerField(verbose_name='prix')),
                ('version', models.IntegerField(verbose_name='auteur du livre')),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='librairie.Categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de parution')),
                ('visible', models.BooleanField(default=True)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librairie.Livre')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='librairie.Profil', verbose_name='auteur du commentaire')),
            ],
            options={
                'verbose_name': 'avis des lecteurs',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=15, verbose_name='numero de téléphone')),
            ],
            options={
                'unique_together': {('nom', 'prenom', 'tel')},
            },
        ),
        migrations.CreateModel(
            name='Avi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(null=True)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librairie.Livre')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='librairie.Profil')),
            ],
        ),
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('somme', models.IntegerField()),
                ('done', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librairie.Client')),
                ('livre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='librairie.Livre')),
            ],
        ),
    ]
