# Generated by Django 2.2.5 on 2019-10-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.CharField(max_length=2083, unique=True),
        ),
    ]
